replicaCount: 1

image:
  repository: ghcr.io/aruiem234/auto_mhddos
  pullPolicy: Always
  tag: latest

args:
  numOfCopies: "2"
  threads: "1000"
  rpc: "200"

resources: {}
# limits:
#   cpu: 1
#   memory: 2Gi
# requests:
#   cpu: 300m
#   memory: 128Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector:
  dedicated: mhddos
tolerations: []
affinity: {}
